### ISSUE TITLE
Global networking management layer

### ISSUE THREAD

**Issue by starphys** [SJSURoboticsTeam/urc-teleoperation-2024#6]
Provides a simplified access layer to network operations, especially writing commands and receiving statuses.

We need to account for inputs from gamepads, serial controllers, and manual input panes. We also need to account for returning data to status panes, and ensure traffic is moving to and from the appropriate subsystems. 

Network operations should occur on a user defined cadence to a user defined IP address. These configuration options can live in a sidebar tab, which may also make a good home for camera IP addresses and similar global networking data.

**Comment by ninaw04** [comment]
merged in network access layer branch, server works with arm, drive, and science commands
